export const data = {
  list: [
    {
      entity: {
        id: 256,
        parentMenuId: 0,
        name: "taskManage",
        icon: "el-icon-news",
        alias: "推送任务",
        state: "ENABLE",
        sort: 1,
        value: null,
        type: "NONE",
        discription: "用于推送任务的菜单",
        createUserId: 1,
      },
      childs: [
        {
          entity: {
            id: 365,
            parentMenuId: 256,
            name: "/taskManage/TaskList",
            icon: "el-icon-user\r\n",
            alias: "任务列表",
            state: "ENABLE",
            sort: 0,
            value: "http://canyuegongzi.xyz/simple-file-center-web/#/fileManage/categoryList?hideMenus=true",
            type: "NONE",
            discription: "任务列表",
            createUserId: 1,
          },
        },
        {
          entity: {
            id: 365,
            parentMenuId: 256,
            name: "/taskManage/AddTask",
            icon: "el-icon-user\r\n",
            alias: "添加任务",
            state: "ENABLE",
            sort: 0,
            value: "http://canyuegongzi.xyz/simple-file-center-web/#/fileManage/categoryList?hideMenus=true",
            type: "NONE",
            discription: "添加任务",
            createUserId: 1,
          },
        },
      ],
    },
    {
      entity: {
        id: 525896,
        parentMenuId: 0,
        name: "configManage",
        icon: "el-icon-news",
        alias: "推送配置",
        state: "ENABLE",
        sort: 2,
        value: null,
        type: "NONE",
        discription: "用于推送任务的菜单",
        createUserId: 1,
      },
      childs: [
        {
          entity: {
            id: 789,
            parentMenuId: 525896,
            name: "/taskManage/TaskEmailConfig",
            icon: "el-icon-s-tools\n\r\n",
            alias: "邮件配置",
            state: "ENABLE",
            sort: 0,
            value: "http://canyuegongzi.xyz/simple-file-center-web/#/fileManage/qiNiuConfig?hideMenus=true",
            type: "NONE",
            discription: "任务配置",
            createUserId: 1,
          }, // /taskManage/TaskMessageConfig
        },
        {
          entity: {
            id: 2568,
            parentMenuId: 525896,
            name: "/taskManage/TaskMessageConfig",
            icon: "el-icon-s-tools\n\r\n",
            alias: "短信配置",
            state: "ENABLE",
            sort: 0,
            value: "http://canyuegongzi.xyz/simple-file-center-web/#/fileManage/qiNiuConfig?hideMenus=true",
            type: "NONE",
            discription: "任务配置",
            createUserId: 1,
          },
        },
        {
          entity: {
            id: 256558,
            parentMenuId: 5256,
            name: "/taskManage/AppRegister",
            icon: "el-icon-s-tools\n\r\n",
            alias: "应用注册",
            state: "ENABLE",
            sort: 0,
            value: "http://canyuegongzi.xyz/simple-file-center-web/#/fileManage/qiNiuConfig?hideMenus=true",
            type: "NONE",
            discription: "应用注册",
            createUserId: 1,
          },
        },
        {
          entity: {
            id: 256558555,
            parentMenuId: 5256,
            name: "/taskManage/peakConfig",
            icon: "el-icon-s-tools\n\r\n",
            alias: "其他配置",
            state: "ENABLE",
            sort: 0,
            value: "http://canyuegongzi.xyz/simple-file-center-web/#/fileManage/qiNiuConfig?hideMenus=true",
            type: "NONE",
            discription: "应用注册",
            createUserId: 1,
          },
        },

      ],
    },
    {
      entity: {
        id: 25621,
        parentMenuId: 0,
        name: "logManage",
        icon: "el-icon-news",
        alias: "任务日志",
        state: "ENABLE",
        sort: 1,
        value: null,
        type: "NONE",
        discription: "用于推送任务的菜单",
        createUserId: 1,
      },
      childs: [
        {
          entity: {
            id: 10,
            parentMenuId: 25621,
            name: "/taskManage/TaskNote",
            icon: "el-icon-s-tools\n\r\n",
            alias: "任务日志",
            state: "ENABLE",
            sort: 0,
            value: "http://canyuegongzi.xyz/simple-file-center-web/#/fileManage/fileList?hideMenus=true",
            type: "NONE",
            discription: "任务日志",
            createUserId: 1,
          },
        },
      ],
    },
  ],
};
